import { Card } from "../types/index";

export const GameCards: Card[] = [
  {
    img: "/assets/card/abnum-b-1.png",
    cardNo: 1,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-2.png",
    cardNo: 2,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-3.png",
    cardNo: 3,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-4.png",
    cardNo: 4,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-5.png",
    cardNo: 5,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-6.png",
    cardNo: 6,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-7.png",
    cardNo: 7,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-8.png",
    cardNo: 8,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-9.png",
    cardNo: 9,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-10.png",
    cardNo: 10,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-11.png",
    cardNo: 11,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-12.png",
    cardNo: 12,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-b-13.png",
    cardNo: 13,
    color: "black",
    cardtype: "/assets/card/abType1.png",
  },
  {
    img: "/assets/card/abnum-r-1.png",
    cardNo: 1,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-2.png",
    cardNo: 2,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-3.png",
    cardNo: 3,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-4.png",
    cardNo: 4,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-5.png",
    cardNo: 5,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-6.png",
    cardNo: 6,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-7.png",
    cardNo: 7,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-8.png",
    cardNo: 8,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-9.png",
    cardNo: 9,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-10.png",
    cardNo: 10,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-11.png",
    cardNo: 11,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-12.png",
    cardNo: 12,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-r-13.png",
    cardNo: 13,
    color: "red",
    cardtype: "/assets/card/abType2.png",
  },
  {
    img: "/assets/card/abnum-b-1.png",
    cardNo: 1,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-2.png",
    cardNo: 2,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-3.png",
    cardNo: 3,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-4.png",
    cardNo: 4,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-5.png",
    cardNo: 5,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-6.png",
    cardNo: 6,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-7.png",
    cardNo: 7,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-8.png",
    cardNo: 8,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-9.png",
    cardNo: 9,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-10.png",
    cardNo: 10,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-11.png",
    cardNo: 11,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-12.png",
    cardNo: 12,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-b-13.png",
    cardNo: 13,
    color: "black",
    cardtype: "/assets/card/abType3.png",
  },
  {
    img: "/assets/card/abnum-r-1.png",
    cardNo: 1,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-2.png",
    cardNo: 2,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-3.png",
    cardNo: 3,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-4.png",
    cardNo: 4,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-5.png",
    cardNo: 5,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-6.png",
    cardNo: 6,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-7.png",
    cardNo: 7,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-8.png",
    cardNo: 8,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-9.png",
    cardNo: 9,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-10.png",
    cardNo: 10,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-11.png",
    cardNo: 11,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-12.png",
    cardNo: 12,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
  {
    img: "/assets/card/abnum-r-13.png",
    cardNo: 13,
    color: "red",
    cardtype: "/assets/card/abType4.png",
  },
];
